PREFIX shacl: <http://www.w3.org/ns/shacl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?property
WHERE {
	?shape1 a shacl:NodeShape;
	  shacl:property [
	    shacl:path ?property
	  ].

	 ?ap1 rdfs:member ?shape1.

	 <https://data.vlaanderen.be/standaarden/> rdfs:member ?ap1.
}
