PREFIX textile: <http://w3id.org/CEON/ontology/textile/>
PREFIX voc: <http://example.com/voc/>

SELECT ?ProductDataSheet ?Property ?Value WHERE {
  ?ProductDataSheet a textile:TextileDataSheet;
     <http://w3id.org/CEON/ontology/resourceODP/isAbout> $product;
     ?Property ?Value .
}
