PREFIX textile: <http://w3id.org/CEON/ontology/textile/>
PREFIX voc: <http://example.com/voc/>

SELECT ?product ?name ?brand WHERE {
  ?product a textile:TextileProduct .
  ?product voc:1100 ?name .
  ?product voc:1101 ?brand .
}
