prefix vc: <https://www.w3.org/2018/credentials#>
prefix schema: <http://schema.org/>

SELECT ?x ?p ?o 
WHERE {

  ?x 
    a vc:VerifiableCredential;
    vc:credentialSubject [
      ?p ?o ;
  	];

    .
}