PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX o: <https://www.example.com/ont/>

SELECT DISTINCT ?componentName
WHERE {
  ?component
    o:name ?componentName ;
	o:has-component-bom ?bom
}
ORDER BY ?componentName
