PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX o: <https://www.example.com/ont/>

SELECT DISTINCT ?materialName
WHERE {
  ?componentMaterialAssoc o:has-material [
    o:name ?materialName
  ]
}
ORDER BY ?materialName
