PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX example: <http://localhost:3000/admin/data/index-example-texon-only#>

SELECT ?object
WHERE {
  example:index-example rdfs:seeAlso ?object .
}
